# -*- coding: utf-8 -*-
"""Building_RAG_Chatbots_for_Technical_Documentation_Samsung_Washing_Machine_Manual (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ntG-sP2ZD5CST_APcrFGKBvc3-Bitsfi

# Building RAG Chatbots for Technical Documentation Samsung Washing Machine Manual

A machine dashboard with lots of new technical features.

You're working for a well-known company Samsung manufacturer who is looking at implementing LLMs into Washing Machine to provide guidance to household users. You've been asked to experiment with integrating washining machine manuals with an LLM to create a context-aware chatbot. They hope that this context-aware LLM can be hooked up to a text-to-speech software to read the model's response aloud.

As a proof of concept, you'll integrate several pages from a washing machine manual that contains machine warning messages and their meanings and recommended actions. This particular manual, stored as an HTML file, `https://www.samsung.com/levant/support/home-appliances/how-to-use-the-various-modes-of-the-washing-machine/`, is from an Samsung, a washing machine manufacturar. Armed with your newfound knowledge of LLMs and LangChain, you'll implement Retrieval Augmented Generation (RAG) to create the context-aware chatbot.

**Note: Although we'll be using the OpenAI API in this project, you need to specify an API key from your OpenAPI portal.**

**What is context-aware chatbot:**


Context awareness is important for creating conversational artificial intelligence (AI) that feels natural, engaging, and intelligent. In a context-aware chatbot, the bot remembers previous interactions and uses that information to inform its responses, much like a human would.

**Dataset input Samsung Washing Machine Manual:**

Download this web page in your local system and then read from relevant address:

https://www.samsung.com/levant/support/home-appliances/how-to-use-the-various-modes-of-the-washing-machine/
"""

# Run this cell to install the necessary packages





# Import the required packages
from langchain_core.prompts import ChatPromptTemplate
# First, understand Prompt Templates: It is used for formatting user input into a suitable prompt for an LLM.
# ChatPromptTemplate: for chat-based prompts with multiple messages.

from langchain_openai import ChatOpenAI, OpenAIEmbeddings
# ChatOpenAI class provides more chat-related methods, such as completion_with_retry,
#  get_num_tokens_from_messages to make it more user-friendly when build chatbot related applications.
# With OpenAI, the input and output are strings, while with ChatOpenAI, the input is a sequence of messages
# and the output is a message.
# They use different API endpoints and the endpoint of OpenAI has received its final
# models like Gemini offer ChatGemini, and OpenAI offers ChatOpenAI.
# These modules are specifically built for chat applications
#  and are optimized for maintaining context and handling extended interactions.

# OpenAI models use advanced algorithms and big data to achieve a much deeper
# and more nuanced representation of the data.
# The model not only analyzes individual words, but also looks at the context in which those words are used
# OpenAI embeddings are based on sophisticated machine learning models that can learn from a huge amount of data.
# This means that they can recognize subtle patterns and relationships in the data
# that go far beyond what could be achieved by simple scaling and dimensioning

from langchain_community.document_loaders import UnstructuredHTMLLoader
# Using UnstructuredHTMLLoader: Extracts plain text content from HTML files.

from langchain_core.runnables import RunnablePassthrough

# First, understand Runnable:It is a unit of work that can be invoked, batched, streamed, transformed and composed.
# In LangChain, a Runnable is a fundamental building block that represents a single task or operation,
# and it’s the core of the Lang Chain Expression Language (LCEL).
# LangChain provides a flexible framework for building LLM-powered applications.
# One of its core features is the concept of Runnables,
#  which are modular units of computation that can be composed together to build chains.
# RunnablePassthrough is the most basic Runnable.
# It simply returns the input as the output. This is useful for debugging, testing, or placeholder purposes.

# If you are using a RunnableSequence, the input flows step-by-step, where the output of one component becomes
# the input to the next. For example, if we start with a country input,
# the first prompt generates some text (e.g., a summary),
# and that output is then passed into the next prompt (e.g., to create a joke or quiz).

# However, there are scenarios where you may want to preserve the original input or
# inspect both the original input and intermediate output. This is where RunnablePassthrough becomes useful.

from langchain_text_splitters import RecursiveCharacterTextSplitter

# RecursiveCharacterTextSplitter
# Splitting text by recursively look at characters.

# Recursively tries to split by different characters to find one that works.

# Chunking involves dividing the document into smaller, more manageable sections that
# fit comfortably within the context window of the large language model.

# Langchain provides users with a range of chunking techniques to choose from. However,
# among these options, the RecursiveCharacterTextSplitter emerges as the favored and strongly recommended method.

# The RecursiveCharacterTextSplitter takes a large text and splits it based on a specified chunk size.
#  It does this by using a set of characters.
#  The default characters provided to it are ["\n\n", "\n", " ", ""].

from langchain_chroma import Chroma

# Chroma is an open source database,
# lets developers build applications including ANN search, image retrieval, RAG,
# and ecommerce recommenders. It’s known as being a lightweight vector database
# that developers can run on a laptop for rapid prototyping, as well as in public or private cloud services.
# Chroma employs the Apache Arrow data format for fast data access.

import requests
import os

# Define the URL and local file path
url = "https://www.samsung.com/levant/support/home-appliances/how-to-use-the-various-modes-of-the-washing-machine/"
file_path = "/content/sample_data/1.html"

# Create the directory if it doesn't exist
os.makedirs(os.path.dirname(file_path), exist_ok=True)

# Download the HTML content and save it to the file
try:
    response = requests.get(url)
    response.raise_for_status() # Raise an exception for HTTP errors (4xx or 5xx)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(response.text)
    print(f"Successfully downloaded {url} to {file_path}")
except requests.exceptions.RequestException as e:
    print(f"Error downloading the file: {e}")
    # Exit or handle the error appropriately if download fails

# Load the HTML as a LangChain document loader
loader = UnstructuredHTMLLoader(file_path=file_path)
machine_docs = loader.load()

"""To get an OpenAI API key, follow these steps:

1. Go to the OpenAI Platform:

OpenAI Platform

2. Sign in with your OpenAI account (or create one).

3. Navigate to the API Keys page:

API Keys Page: https://platform.openai.com/api-keys?utm_source=chatgpt.com

4. Click "Create new secret key".

5. Copy the key immediately and store it securely. It will look similar to:
sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

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
"""

import os

os.environ["OPENAI_API_KEY"] = "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" # Replace with your actual OpenAI API Key

"""### Action Required: Replace OpenAI API Key

**Please go to the cell directly above this markdown cell (`-_mVTSr6AhO2`) and replace `<YOUR_OPENAI_API_KEY_HERE>` with your actual OpenAI API key.**

After replacing the placeholder, rerun the cell and then proceed to execute the subsequent cells.

**Important:** Ensure your API key is correctly entered to resolve the `AuthenticationError`.
"""

# Load the models required to complete the exercise
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)

# Temperature in deep learning is a parameter usually used to adjust the probability distribution
# of the predicted outputs. It is also known as softmax temperature or softmax scaling.
# In simple terms,
# it controls the level of confidence that a neural network has in its predictions.
# It helps to increase the diversity of the model’s outputs.

# For temperature in OpenAI chat request, “higher values like 0.8 will make the output more random,
# while lower values like 0.2 will make it more focused and deterministic”.


# Temperature is a parameter that controls the “creativity” or randomness of the text generated by GPT.
# A higher temperature (e.g., 0.7) results in more diverse and creative output, while a lower temperature
#  (e.g., 0.2) makes the output more deterministic and focused.

# Temperature value less than 1 makes the model more deterministic
# because if you divide a number with a value less than 1, you get a greater number.


embeddings = OpenAIEmbeddings(model="text-embedding-3-small", openai_api_key=os.environ["OPENAI_API_KEY"])

# OpenAI models use advanced algorithms and big data to achieve a much deeper
# and more nuanced representation of the data.
# The model not only analyzes individual words, but also looks at the context in which those words are used
# OpenAI embeddings are based on sophisticated machine learning models that can learn from a huge amount of data.
# This means that they can recognize subtle patterns and relationships in the data
# that go far beyond what could be achieved by simple scaling and dimensioning

"""Verify:

https://platform.openai.com/settings/organization/billing/overview?utm_source=chatgpt.com

1. A payment method is attached.
2. Your account has available credits.
3. Monthly spending limit is not set to $0.
"""

# Load the models required to complete the exercise
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)
embeddings = OpenAIEmbeddings(model="text-embedding-3-small", openai_api_key=os.environ["OPENAI_API_KEY"])

# Initialize RecursiveCharacterTextSplitter to make chunks of HTML text
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)

# Because RAG pipelines often rely on retrieval from vector databases and large language models (LLMs)
# with limited context windows,
# smart chunking can make all the difference in delivering relevant, context-rich answers.

# Chunking is the process of breaking a large piece of text into smaller,
# manageable pieces to make it easier to process and analyze.
# The chunk size refers to the maximum number of characters or tokens allowed in a single chunk.

# What is Chunk Overlap?

# Chunk Overlap refers to the number of characters or tokens shared between consecutive chunks.
# Overlapping ensures that important context is not lost when diving the text into smaller parts.

# Common values range from 200 to 500 tokens per chunk for embedding tasks.
# Chunk Overlap: Generally, overlap is set to 10%-20% of the chunk size to ensure continuity.


# Split the machine documents with text_splitter
splits = text_splitter.split_documents(machine_docs)

# Initialize Chroma vectorstore with documents as splits and using OpenAIEmbeddings
vectorstore = Chroma.from_documents(documents=splits, embedding=embeddings)

# Setup vectorstore as retriever
# By calling .as_retriever(), you wrap the complex vector database
# into a simple component that plugs directly into LangChain chains and LangChain Expression Language (LCEL).
retriever = vectorstore.as_retriever()

# Define RAG prompt
prompt = ChatPromptTemplate.from_template("""You are an assistant for question-answering tasks.
Use the following pieces of retrieved context to answer the question.
If you don't know the answer, just say that you don't know.
Use three sentences maximum and keep the answer concise.\nQuestion: {question} \nContext: {context} \nAnswer:""")

# Setup the chain
# you have to send question to the vector store as well as to the prompt later in the pipeline.
# Using "question": RunnablePassthrough() ensures the original question is retained for the prompt,
# whereas without it the "question" key would not be available during prompt construction.

rag_chain = (
    {"context": retriever , "question": RunnablePassthrough()}
    | prompt
    | llm
)

# When working with LCEL we may find that we need to modify the flow of values,
# or the values themselves as they are passed between components — for this, we can use runnables.

# Initialize query
query = "What is the cycle for DRUM CLEAN?"

# Invoke the query
answer = rag_chain.invoke(query).content
print(answer)

# Initialize query
# query = "What should I do for DAILY WASH?"

# Invoke the query
answer = rag_chain.invoke(query).content
print(answer)

"""Learning resources: https://academy.langchain.com/courses/take/langgraph-essentials-python/texts/69422269-getting-set-up"""

